version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - botanika-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=production
      - LINE_NOTIFY_TOKEN=${LINE_NOTIFY_TOKEN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - botanika-network

networks:
  botanika-network:
    driver: bridge
